### ISSUE TITLE
Can you show annexed file size in a dired buffer

### ISSUE THREAD

**Issue by QiangF** [mm--/dot-emacs#2]
I see you have made many modifications to the git-annex package. Maybe you can add such feature. Currently the dired buffer of locked files are just symlinks, the file size column is useless.

**Comment by mm--** [comment]
Yeah, that's definitely one of the issues I've been having myself. A couple workarounds are: 

1. To edit the `ls` flags with `C-u s` and add `L` which dereferences symlinks. The problem with this is that `ls` will then complain about any symlinks that don't exist. So I don't tend to use this option much.
2. In `eshell` I've [defined a command called `gaf` (for "git annex files")](https://github.com/mm--/dot-emacs/blob/f1f828d5047b2f255676564a33a772e9d9658f28/jmm-emacs.org#git-annex-utilities) which allows me to filter based on `git-annex-matching-options`. So in `eshell` I can write `du -hL ${gaf --in=here} | sort -h` and that will show all the present files and sort them by their file size.

In the future, I'd like to take a look at `dired-du-mode` which adds file size to directories, and adapt it to git annex. Two ways to get the git-annex file size are to either get the size of the dereferenced link (this only works if that file is in your current repository), or to use the symlink name itself (the SHA256E backend includes a string of the form `s12345...` which is the file size in bytes (this of course only works on that backend and not for URL backends).

**Comment by mm--** [comment]
It looks like `dired-du-mode` is having to do a whole lot just to replace file sizes. For example, it has to calculate new column widths and replace the sizes of every file (not just directories).

In the meantime I've [made a function called `jmm/dired-git-annex-print-human-file-size`](https://github.com/mm--/dot-emacs/blob/33c23e12a3fc9a58e83b79f3d3f6f7e77aa18c82/jmm-emacs.org#get-git-annex-file-sizes) which you might find useful.  It prints the file size of the git-annex file at point in `dired`, and I currently have it bound to `@ s`.

Potentially, we could use `jmm/git-annex-file-size` to advise the function `dired-du-get-file-info` so `dired-du-mode` also replaces git-annex symlink sizes. However, I also tend to avoid using `dired-du-mode` as it takes it while to calculate directory sizes and blocks Emacs during the calculation. There's probably some setting I could tweak to make it faster, but I haven't looked into it much.

**Comment by mm--** [comment]
Okay, I've actually figured it out! :grin: 

I just [wrote a function `jmm/dired-git-annex-add-real-file-sizes`](https://github.com/mm--/dot-emacs/blob/c77a85fa333a88de5d416e967509e74a18901d9c/jmm-emacs.org#show-git-annex-file-sizes-in-dired) that goes through the whole `dired` buffer, replaces git-annex symlink sizes with human readable file sizes (even if they're dropped and not in the current repo! [provided they use the SHA256E backend]), and then realigns everything.

I didn't end up having to use `dired-du-mode` at all. Instead, I based it off of `dired--align-all-files`.

I have the function bound to `@ S` and it seems like it's working pretty well. Theoretically you could even add it to your `dired-mode-hook` to have it done automatically.

Let me know how it works for you. Marking this issue as closed. :confetti_ball:

**Comment by QiangF** [comment]
Amazing! I still need to find some time to digest it. Can you add sort by file size to an annex dired buffer?

**Comment by mm--** [comment]
Unfortunately not directly. I'm not sure if the sorting is done via `ls` before it's passed to `dired`. This workaround also just edits the column, but not how Elisp sees the `file-attributes` of `git-annex` files.

However! If you wanted to create a `dired` buffer directly with files sorted by size, it turns out that `dired` can take in a list of files (with the first element being the name of the `dired` buffer).
So, what I do is I run `eshell` in the directory I'm interested in and then I run:
`dired ${cons "some-dired-name" ${du -hL ${gaf --in=here} | sort -h | awk '{print $2}'}}`

That's really complicated, but what it does is construct a list of files in the current repository sorted by size, then adds "some-dired-name" (or whatever you want the `dired` buffer to be called) to the beginning of the list, then calls `dired` on that list. What you get then is a `dired` buffer sorted (ascending) by file size.

**Comment by QiangF** [comment]
The variable 'diredp-font-lock-keywords-1 in dired+ has a higher priority than 'dired-font-lock-keywords. 

To hide the long symlinks, I used to have font-lock-keywords in dired buffer set with:

    (progn
    (add-to-list 'diredp-font-lock-keywords-1
                (list " -> .*\\.git/annex/"
                        '("\\(.+\\)\\( -> .+\\)" (dired-move-to-filename) nil
                        (1 git-annex-dired-annexed-unavailable)
                        (2 git-annex-dired-annexed-invisible))))
    (add-to-list 'diredp-font-lock-keywords-1
                (list 'git-annex-lookup-file
                        '("\\(.+\\)\\( -> .+\\)" (dired-move-to-filename) nil
                        (1 git-annex-dired-annexed-available)
                          (2 git-annex-dired-annexed-invisible)))))

The above setting doesn't work with this show file size hack.  I modified diredp-font-lock-keywords-1 according to your .emacs file.

    (progn                                
    (add-to-list 'diredp-font-lock-keywords-1
        (list "^[*].+ -> .*\\.git/annex/"
            '("\\(.+\\)\\( -> .+\\)" (dired-move-to-filename) nil
            (1 dired-marked-face)
            (2 git-annex-dired-annexed-invisible))))
    (add-to-list 'diredp-font-lock-keywords-1
        (list "^[D].+ -> .*\\.git/annex/"
            '("\\(.+\\)\\( -> .+\\)" (dired-move-to-filename) nil
            (1 dired-flagged-face)
            (2 git-annex-dired-annexed-invisible)))))

Now with the above setting the symlinks fails to hide.

**Comment by QiangF** [comment]
Seems this regex doesn't work with dired+.

    "^[*].+ -> .*\\.git/annex/"

If I have dired+ enabled the show size won't work.
I can get my symlink path short with:

    (eval-after-load "dired+"
    '(progn                                
        ;; the following conflict with show size hack
        (add-to-list 'diredp-font-lock-keywords-1
        (list "^[ ].* -> .*\\.git/annex/"
        '("\\(.+\\)\\( -> .+\\)" (dired-move-to-filename) nil
            (1 dired-symlink-face)
            (2 git-annex-dired-annexed-invisible))))
        (add-to-list 'diredp-font-lock-keywords-1
        (list "^[*].* -> .*\\.git/annex/"
        '("\\(.+\\)\\( -> .+\\)" (dired-move-to-filename) nil
            (1 dired-marked-face)
            (2 git-annex-dired-annexed-invisible))))
        (add-to-list 'diredp-font-lock-keywords-1
        (list "^[D].+ -> .*\\.git/annex/"
        '("\\(.+\\)\\( -> .+\\)" (dired-move-to-filename) nil
            (1 dired-flagged-face)
            (2 git-annex-dired-annexed-invisible))))))

**Comment by mm--** [comment]
Hmm... Interesting. I haven't used `dired+` so I'm not sure what it's doing differently. It doesn't seem like font-lock settings should change the size column stuff (font-lock just hides information by making the text "invisible" but not deleting it, so it shouldn't affect how to find git-annex files.)

In regards to your earlier question about sorting by git-annex file size, I'm starting to add functions to do just that. A simple version of that function is [here](https://github.com/mm--/dot-emacs/blob/4e861148a67c8eee14076d80df6b0f7a4a7c48d3/jmm-emacs.org#sort-dired-by-file-size). It just uses `sort-subr` to rearrange lines in `dired` based on `jmm/dired-file-size`.

**Comment by mm--** [comment]
I should also note that my modifications to `dired-font-lock-keywords` is just to get marked files to appear properly. So you should add your previous modifications on top of these ones.
I wonder if you do something like `toggle-debug-on-error` if you'll see that the file size stuff fails for some reason. There may be some dired text properties the script is expecting that for some reason don't appear with `dired+`.

Anyway, hope you found a solution. Sorry I couldn't be of more help.

--Josh

**Comment by QiangF** [comment]
Thank you for the tip.

I think I have found the issue: in jmm/dired-git-annex-add-real-file-sizes, my directory-listing-before-filename-regexp doesn 't have a match on the file line.
Because I have chinese character in the date column.

  lrwxrwxrwx  1 q q  199 9月  18 17:13 someday.org -> ../.git/annex/objects/FJ/j1/SHA256E-s370776--ef42ecba8cd3d9263bdf69b8a62459131a8c0cfefdc5d91053dda5c86973d5ec.org/SHA256E-s370776--ef42ecba8cd3d9263bdf69b8a62459131a8c0cfefdc5d91053dda5c86973d5ec.org

I will try using the english locale.

**Comment by QiangF** [comment]
It finally works, by setq dired-listing-switches "-alh --group-directories-first --time-style=iso"
Thanks a lot.
